### PR TITLE
Fix #2, Keen IO/foursquare branding

### LINKED ISSUE #2: Heroku button does not work (invalid JSON)
screen shot 2015-08-28 at 4 04 29 pm

### PR DESCRIPTION
**Pull request by adamd**

### CODE REVIEW

**Comment by cp** [comment]
@adamd just saw this. :cry: awesome! :shipit:

**Comment by adamd** [comment]
I wondered! :hand: high five!

**Comment by cp** [comment]
@adamd but... where's "Fix #1"?

**Comment by cp** [comment]
oooh, issue #2

**Comment by cp** [comment]
i'm dumb

**Comment by cp** [comment]
where am I

**Pull request merged**
